version: '3.9'  # Specify the version of the Compose file

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kardb  # This creates the 'mydb' database
    ports:
      - "3306:3306"  # Expose MySQL port
    volumes:
      - type: bind
        source: C:\Users\mkabd\IdeaProjects\KazArthroRegistry\docker
        target: /var/lib/mysql
